version: '3'
services:
  reverseproxy:
    build:
      context: .
    image: phil092/udagram-reverseproxy:latest
  backend_user:
    build:
      context: ../../udagram-restapi-user
    image: phil092/udagram-restapi-user:latest
  backend_feed:
    build:
      context: ../../udagram-restapi-feed
    image: phil092/udagram-restapi-feed:latest
  frontend:
    build:
      context: ../../udagram-frontend
    image: phil092/udagram-frontend:latest
